name: Deploy static website

on:
  push:
    branches:
      - main  # 在推送到 main 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages  # 使用配置的 github-pages 环境
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Replace API keys
      run: |
        sed -i 's/GOOGLE_MAPS_API_KEY_PLACEHOLDER/${{ secrets.GOOGLE_MAPS_API_KEY }}/g' index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3  # 使用 GitHub Actions 部署到 GitHub Pages
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # 部署根目录
